# Generated by Django 4.2.19 on 2025-02-25 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title', max_length=255)),
                ('text', models.TextField(help_text='Banner text')),
                ('image', models.ImageField(help_text='Banner image', upload_to='main_page/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text', max_length=50)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Calculator section title', max_length=255)),
                ('background_image', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='main_page/calculator/')),
            ],
        ),
        migrations.CreateModel(
            name='CardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide this section')),
            ],
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='FAQ title', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Address', max_length=255)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MainScreenFeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.button')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TitreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('text', models.TextField(help_text='Section text')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeFeedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('subscriber_count', models.CharField(blank=True, help_text='Subscriber count with label', max_length=50)),
                ('channel_link', models.URLField(blank=True, help_text='YouTube channel link')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(blank=True, help_text='Video preview image', null=True, upload_to='main_page/youtube_previews/')),
                ('title', models.CharField(help_text='Video title', max_length=255)),
                ('views_info', models.CharField(blank=True, help_text='Views and time info', max_length=255)),
                ('video_link', models.URLField(help_text='YouTube video link')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='integration.youtubefeedsection')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Social media icon', upload_to='main_page/social_icons/')),
                ('url', models.URLField(help_text='Social media link')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='integration.footer')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('rating_icon', models.ImageField(blank=True, help_text='Company icon', null=True, upload_to='icons/')),
                ('rating_star', models.DecimalField(blank=True, decimal_places=1, help_text='Rating 0-5', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.button')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=255)),
                ('rating', models.PositiveIntegerField(help_text='Rating (0-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text='Review text')),
                ('car_name', models.CharField(help_text='Car name', max_length=255)),
                ('car_image', models.ImageField(help_text='Car image (165x165)', upload_to='car_images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.reviewsection')),
            ],
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Pricing section title', max_length=255)),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.button')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Plan title', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='integration.pricingsection')),
            ],
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Feature text', max_length=255, null=True)),
                ('star_rating', models.PositiveIntegerField(blank=True, help_text='Star rating (1-3)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='integration.pricingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(help_text='Partner logo (190x120)', upload_to='main_page/partners/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='integration.partnersection')),
            ],
        ),
        migrations.CreateModel(
            name='MainSelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text', max_length=255)),
                ('main_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='integration.mainselect')),
            ],
        ),
        migrations.CreateModel(
            name='MainScreenFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Icon', upload_to='main_page/icons/')),
                ('text', models.CharField(help_text='Text', max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.mainscreenfeatureblock')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('background_image', models.ImageField(blank=True, default=None, help_text='Background image', null=True, upload_to='main_page/backgrounds/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating 0.0-5.0', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Main page title', max_length=255)),
                ('video_url', models.URLField(blank=True, help_text='Video URL')),
                ('video_text', models.CharField(blank=True, help_text='Video text', max_length=255)),
                ('video_preview', models.ImageField(blank=True, help_text='Video preview img', null=True, upload_to='main_page/video_previews/')),
                ('banner_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_section_1', to='integration.bannersection')),
                ('banner_section_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_section_2', to='integration.bannersection')),
                ('calculator_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.calculatorsection')),
                ('faq_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.faqsection')),
                ('feature_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page_feature', to='integration.cardsection')),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('main_screen_feature_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.mainscreenfeatureblock')),
                ('main_screen_select', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.mainselect')),
                ('marketing_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page_marketing', to='integration.cardsection')),
                ('partner_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.partnersection')),
                ('pricing_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.pricingsection')),
                ('review_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.reviewsection')),
                ('steps_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page_steps', to='integration.cardsection')),
                ('titre_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titresection')),
                ('why_chose_us_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page_why_chose_us', to='integration.cardsection')),
                ('youtube_feed_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.youtubefeedsection')),
            ],
        ),
        migrations.CreateModel(
            name='FooterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating (0-5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.CharField(help_text='Footer note text', max_length=255)),
                ('footer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='integration.footer')),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], default='customer', help_text='FAQ category', max_length=50)),
                ('question', models.CharField(help_text='Question', max_length=255)),
                ('answer', models.TextField(help_text='Answer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integration.faqsection')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Icon', null=True, upload_to='card/icons/')),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle', max_length=255)),
                ('text', models.TextField(help_text='Text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='integration.cardsection')),
            ],
        ),
        migrations.AddField(
            model_name='bannersection',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.button'),
        ),
    ]
