# Generated by Django 4.2.19 on 2025-02-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_alter_mainscreenfeature_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcard',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='integration.reviewsection'),
        ),
    ]
