# Generated by Django 4.2.19 on 2025-02-27 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_reviewcard_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Single image', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TitleDescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('description', models.TextField(help_text='Page description')),
            ],
        ),
        migrations.AddField(
            model_name='footer',
            name='contacts_title',
            field=models.CharField(blank=True, help_text='Pour un contact rapide, voici nos informations :', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_help_text',
            field=models.CharField(blank=True, help_text='(Lundy au bended, 9h-18h)', max_length=100),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('background_image', models.ImageField(blank=True, default=None, help_text='Background image', null=True, upload_to='main_page/backgrounds/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating 0.0-5.0', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Main page title', max_length=255)),
                ('video_url', models.URLField(blank=True, help_text='Video URL')),
                ('video_text', models.CharField(blank=True, help_text='Video text', max_length=255)),
                ('video_preview', models.ImageField(blank=True, help_text='Video preview img', null=True, upload_to='main_page/video_previews/')),
                ('faq_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.faqsection')),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('main_screen_feature_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.mainscreenfeatureblock')),
                ('main_screen_select', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.mainselect')),
            ],
        ),
    ]
