# Generated by Django 4.2.19 on 2025-02-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_imageblock_titledescriptionblock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='main_screen_feature_block',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='main_screen_select',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='video_preview',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='video_text',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='video_url',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='image_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.imageblock'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title_desc_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titledescriptionblock'),
        ),
        migrations.CreateModel(
            name='Franchises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.bannersection')),
                ('faq_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.faqsection')),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('image_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.imageblock')),
                ('title_desc_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titledescriptionblock')),
                ('why_need_franchise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.cardsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstimationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('faq_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.faqsection')),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('image_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.imageblock')),
                ('title_desc_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titledescriptionblock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
