# Generated by Django 4.2.19 on 2025-03-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_tag_blogpage_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='why_chose_us_section',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='why_chose_us_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.cardsection'),
        ),
    ]
