# Generated by Django 4.2.19 on 2025-03-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_remove_article_why_chose_us_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='integration.blogpage'),
            preserve_default=False,
        ),
    ]
