# Generated by Django 4.2.19 on 2025-03-05 14:20

import apps.integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_alter_article_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainscreenfeature',
            name='icon',
            field=models.FileField(help_text='Icon', upload_to='main_page/icons/', validators=[apps.integration.models.svg_validator]),
        ),
    ]
