# Generated by Django 4.2.19 on 2025-03-05 14:25

import apps.integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_alter_mainscreenfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.FileField(blank=True, help_text='Icon', null=True, upload_to='card/icons/', validators=[apps.integration.models.image_validator]),
        ),
        migrations.AlterField(
            model_name='mainscreenfeature',
            name='icon',
            field=models.FileField(help_text='Icon', upload_to='main_page/icons/', validators=[apps.integration.models.image_validator]),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='rating_icon',
            field=models.FileField(blank=True, help_text='Company icon', null=True, upload_to='icons/', validators=[apps.integration.models.image_validator]),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(help_text='Social media icon', upload_to='main_page/social_icons/', validators=[apps.integration.models.image_validator]),
        ),
    ]
