# Generated by Django 4.2.19 on 2025-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0011_alter_card_icon_alter_mainscreenfeature_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubefeedsection',
            name='duration',
            field=models.CharField(blank=True, help_text='6:32 (for example)', max_length=8),
        ),
    ]
