# Generated by Django 4.2.19 on 2025-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0012_youtubefeedsection_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubefeedsection',
            name='duration',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='duration',
            field=models.CharField(blank=True, help_text='6:32 (for example)', max_length=8),
        ),
    ]
