# Generated by Django 4.2.19 on 2025-03-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0013_remove_youtubefeedsection_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='banner_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.bannersection'),
        ),
    ]
