# Generated by Django 4.2.19 on 2025-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0014_blogpage_banner_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parsed_text',
            field=models.TextField(blank=True, help_text='Parsed article text', max_length=5000),
        ),
    ]
