# Generated by Django 4.2.19 on 2025-03-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0015_article_parsed_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='plan',
            field=models.TextField(blank=True, help_text='Article plan', max_length=5000),
        ),
    ]
