# Generated by Django 4.2.19 on 2025-03-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0016_alter_article_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQAlternativeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question', max_length=255)),
                ('answer', models.TextField(help_text='Answer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_items', to='integration.faqsection')),
            ],
        ),
    ]
