# Generated by Django 4.2.19 on 2025-03-07 17:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0017_faqalternativeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titresection',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Section text', max_length=10000),
        ),
    ]
