# Generated by Django 4.2.19 on 2025-03-07 17:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0018_alter_titresection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titresection',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Section text', max_length=10000),
        ),
    ]
