# Generated by Django 4.2.19 on 2025-03-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0019_alter_titresection_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('titre_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titresection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('titre_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titresection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title', max_length=100)),
                ('seo_description', models.CharField(blank=True, help_text='SEO Description', max_length=500)),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.footer')),
                ('titre_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.titresection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
