# Generated by Django 4.2.19 on 2025-03-08 17:12

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_titresection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titresection',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Section text', max_length=20000),
        ),
        migrations.AlterField(
            model_name='titresection',
            name='title',
            field=models.CharField(blank=True, help_text='Section title', max_length=255),
        ),
    ]
