# Generated by Django 4.2.19 on 2025-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0022_alter_titresection_text_alter_titresection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersection',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this section'),
        ),
    ]
