# Generated by Django 4.2.19 on 2025-03-09 15:17

from django.db import migrations
import django_ckeditor_5.fields
import trix_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0023_partnersection_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Article text', max_length=20000),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=trix_editor.fields.TrixEditorField(blank=True, help_text='Article text', max_length=20000),
        ),
    ]
