# Generated by Django 4.2.19 on 2025-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0024_article_text2_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parsed_text2',
            field=models.TextField(blank=True, help_text='Parsed article text', max_length=20000),
        ),
        migrations.AlterField(
            model_name='article',
            name='parsed_text',
            field=models.TextField(blank=True, help_text='Parsed article text', max_length=20000),
        ),
    ]
