# Generated by Django 4.2.19 on 2025-03-09 16:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0025_article_parsed_text2_alter_article_parsed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='parsed_text2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text2',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Article text', max_length=20000),
        ),
    ]
