# Generated by Django 4.2.19 on 2025-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0026_remove_article_parsed_text2_remove_article_text2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
