# Generated by Django 4.2.19 on 2025-02-10 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('auto_mark', models.CharField(max_length=50)),
                ('auto_model', models.CharField(max_length=50)),
                ('auto_year', models.PositiveIntegerField()),
                ('auto_km', models.PositiveIntegerField()),
                ('general_condition', models.CharField(max_length=50)),
                ('internal_state', models.CharField(max_length=50)),
                ('accident', models.CharField(max_length=50)),
                ('features', models.JSONField(blank=True, default=None, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('code_postal', models.CharField(max_length=10)),
                ('api_received', models.BooleanField(default=False)),
                ('formtype', models.CharField(max_length=50)),
                ('api_data', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'DataHistory',
                'verbose_name_plural': 'DataHistories',
                'ordering': ['-id'],
            },
        ),
    ]
