# Generated by Django 4.2.19 on 2025-03-10 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(help_text='Nom complet *', max_length=200)),
                ('email', models.EmailField(help_text='Adresse email *', max_length=200)),
                ('phone', models.CharField(help_text='Numéro de téléphone *', max_length=20)),
                ('region', models.CharField(help_text='Ville et région souhaitées pour la franchise *', max_length=400)),
                ('experience', models.TextField(help_text='Expérience professionnelle (secteurs pertinents)', max_length=2000)),
                ('budget', models.CharField(choices=[('entre_20000_et_35000', 'Entre 20 000 € et 35 000 €'), ('_35000_et_50000', '35 000 € et 50 000 €'), ('plus_de_50000', 'Plus de 50 000 €')], default='entre_20000_et_35000', help_text='Budget disponible pour l’investissement', max_length=30)),
                ('message', models.TextField(help_text='Message (facultatif)', max_length=5000)),
            ],
            options={
                'verbose_name': 'Potential franchise',
                'verbose_name_plural': 'Potential franchises',
                'ordering': ['-id'],
            },
        ),
    ]
