# Generated by Django 4.2.19 on 2025-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_potentialfranchise_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialfranchise',
            name='budget',
            field=models.CharField(choices=[('entre_20000_et_35000', 'Entre 20 000 € et 35 000 €'), ('_35000_et_50000', '35 000 € et 50 000 €'), ('plus_de_50000', 'Plus de 50 000 €')], help_text='Budget disponible pour l’investissement', max_length=30),
        ),
    ]
