# Generated by Django 4.2.19 on 2025-05-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_potentialfranchise_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialfranchise',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='potentialfranchise',
            name='region',
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='age',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='candidate_type',
            field=models.CharField(default='-', help_text='Quand souhaitez-vous démarrer ?', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='city',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='city_for_franchise',
            field=models.CharField(default='-', help_text='Dans quelle ville/village souhaitez-vous vous implanter ? *', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='engagement',
            field=models.CharField(default='-', help_text='Êtes-vous prêt à vous engager à plein temps dans le projet ?', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='experience_auto',
            field=models.CharField(blank=True, help_text='Avez-vous une expérience dans le secteur automobile ? *', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='experience_commerciale',
            field=models.CharField(default='-', help_text='Avez-vous une expérience commerciale ?', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='experience_entrepreneur',
            field=models.CharField(default='-', help_text='Êtes-vous déjà entrepreneur ou indépendant ?', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='formtype',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='projet',
            field=models.CharField(default='-', help_text='Quel est votre projet ?', max_length=100),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='potentialfranchise',
            name='start_timing',
            field=models.CharField(default='-', help_text='Quand souhaitez-vous démarrer ?', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='budget',
            field=models.CharField(blank=True, help_text='Quelle est votre capacité d’investissement immédiate ?', max_length=100, null=True),
        ),
    ]
