# Generated by Django 4.2.19 on 2025-05-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_potentialfranchise_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialfranchise',
            name='candidate_type',
            field=models.CharField(help_text='Quand souhaitez-vous démarrer ?', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='city_for_franchise',
            field=models.CharField(help_text='Dans quelle ville/village souhaitez-vous vous implanter ? *', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='engagement',
            field=models.CharField(help_text='Êtes-vous prêt à vous engager à plein temps dans le projet ?', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='experience_commerciale',
            field=models.CharField(help_text='Avez-vous une expérience commerciale ?', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='experience_entrepreneur',
            field=models.CharField(help_text='Êtes-vous déjà entrepreneur ou indépendant ?', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='formtype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='projet',
            field=models.CharField(help_text='Quel est votre projet ?', max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='start_timing',
            field=models.CharField(help_text='Quand souhaitez-vous démarrer ?', max_length=100),
        ),
    ]
