# Generated by Django 4.2.19 on 2025-05-10 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_potentialfranchise_candidate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(help_text='Nom complet *', max_length=200)),
                ('email', models.EmailField(help_text='Adresse email *', max_length=200)),
                ('telephone', models.CharField(help_text='Numéro de téléphone *', max_length=200)),
                ('purpose', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, max_length=5000)),
                ('formtype', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='potentialfranchise',
            name='phone',
            field=models.CharField(help_text='Numéro de téléphone *', max_length=200),
        ),
    ]
